on: [push, pull_request]
name: Cover It Up
jobs:
  coveritup:
    strategy:
      matrix:
        go-version: [latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}

      - name: Install Tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Test Prepare
        run: |
          mkdir -p dist/
          echo "hello" > dist/index.html

      - run: go mod tidy
      - run: golangci-lint run ./...
      - run: go build
      - run: go test ./...
