on: [push, pull_request]
name: Cover It Up
jobs:
  coveritup:
    strategy:
      matrix:
        go-version: [latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}

      - name: Install Tools
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          curl -sLk https://raw.githubusercontent.com/kevincobain2000/cover-totalizer/master/install.sh | sh
      - name: Test Prepare
        run: |
          mkdir -p dist/
          echo "hello" > dist/index.html

      - name: Test
        uses: kevincobain2000/action-coveritup@v2
        with:
          type: go-test-run-time
          command: go test -race -v ./... -count=1 -coverprofile=coverage.out
          record: runtime

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: unit-test-run-time

      - name: Build Time
        uses: kevincobain2000/action-coveritup@v2
        with:
          command: go build -o main main.go
          record: runtime
          type: build-time

      - name: Coveritup
        uses: kevincobain2000/action-coveritup@v2
        with:
          type: coverage
          command: ./cover-totalizer coverage.xml

      - uses: kevincobain2000/action-coveritup@v1
        with:
          type: coverage

      - name: Go Binary Size
        uses: kevincobain2000/action-coveritup@v2
        with:
          type: go-binary-size
          command: du -sk main | awk '{print $1}'

      - name: Number of dependencies
        uses: kevincobain2000/action-coveritup@v2
        with:
          type: go-mod-dependencies
          command: go list -m all|wc -l|awk '{$1=$1};1'

      - name: Number of GO Sec issues
        uses: kevincobain2000/action-coveritup@v2
        with:
          type: go-sec-issues
          command: gosec -no-fail --quiet ./...|grep Issues | tail -1 |awk '{print $3}'

      - uses: kevincobain2000/action-coveritup@v2
        with:
          pr_comment: true
